# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6125dd866cd796bc235d56234b2e504b6dfbd20749c361c5f56deb983d477aedfbc24785cab2911309fb45b01c036c667a26c1e3cc82c1a39f476cf26c93e0b

test:
  secret_key_base: 6e0de5e36fb8fc8a63fc6a1fb81f19e173d6568258655dd4cf5a4ba76891bada9580ae5709c08ef92d2fa9eb9218a94e27b9d0d639f84adc6fea54773937bfd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
